{
    "id": "CVE-2016-1902",
    "modified": "2021-11-17T23:04:26Z",
    "published": "2021-11-17T23:04:26Z",
    "aliases": [],
    "related": [],
    "summary": "CVE-2016-1902: SecureRandom's fallback not secure when OpenSSL fails ",
    "details": "",
    "affected": {
        "package": {
            "ecosystem": "Packagist",
            "name": "symfony\/symfony",
            "purl": "pkg:packagist\/symfony\/symfony"
        },
        "ranges": {
            "type": "SEMVER",
            "events": [
                {
                    "introduced": ">=2.3.0"
                },
                {
                    "fixed": "<2.3.37"
                },
                {
                    "introduced": ">=2.4.0"
                },
                {
                    "fixed": "<2.5.0"
                },
                {
                    "introduced": ">=2.5.0"
                },
                {
                    "fixed": "<2.6.0"
                },
                {
                    "introduced": ">=2.6.0"
                },
                {
                    "fixed": "<2.6.13"
                },
                {
                    "introduced": ">=2.7.0"
                },
                {
                    "fixed": "<2.7.9"
                }
            ]
        }
    },
    "references": [
        {
            "type": "ADVISORY",
            "url": "https:\/\/symfony.com\/cve-2016-1902"
        },
        {
            "type": "PACKAGE",
            "url": "https:\/\/packagist.org\/packages\/symfony\/symfony"
        }
    ]
}